language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential cmake libcairo2-dev libpango1.0-dev libssl-dev libjpeg-dev libgif-dev librsvg2-dev
  - npm -g install yarn
  - yarn global add jest-dom
  - yarn global add react-scripts
  - yarn global add canvas

before_script:
  - cd client
  - yarn

script:
  - yarn test
  - yarn run build
