// ACTION TYPES
export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE';
export const HANDLE_BUTTON_GROUP_CHANGE = 'HANDLE_BUTTON_GROUP_CHANGE';
export const HANDLE_FEVER = 'HANDLE_FEVER';
export const HANDLE_HOURS = 'HANDLE_HOURS';
export const HANDLE_MINUTES = 'HANDLE_MINUTES';
export const HANDLE_SLIDER = 'HANDLE_SLIDER';
export const HANDLE_SYMPTOMS = 'HANDLE_SYMPTOMS';
export const HANDLE_ADDITIONAL_INFO = 'HANDLE_ADDITIONAL_INFO';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const GET_SYMPTOM_TRACKER_STATE = 'GET_SYMPTOM_TRACKER_STATE';
export const GET_CHECKBOX_BUTTON_STATE = 'GET_CHECKBOX_BUTTON_STATE';
